class Translator:
    """
    Translation manager for multi-language support.
    Handles all UI text in multiple languages.
    """
    def __init__(self):
        """Initialize translator with default language English."""
        self.lang = "en"
        self.texts = {
            "en": {
                "title": "Xiangqi Analysis",
                "best_move": "Best move:",
                "score": "Score:",
                "analyze": "ANALYZE",
                "flip": "FLIP BOARD",
                "reset": "RESET",
                "undo": "UNDO",
                "thinking": "Analyzing...",
                "error": "Engine error",
                "ready": "✓ READY",
                "no_move": "✗ NO MOVE",
                "invalid": "✗ INVALID",
                "no_piece": "✗ NO PIECE",
                "engine_error": "✗ ENGINE ERROR",
                "analyzing": "⚙ ANALYZING...",
                "starting": "⚙ STARTING...",
                "undo_done": "↩ UNDO",
                "control_panel": "⚙ CONTROL PANEL",
                "move_list": "MOVE LIST",
                "best_moves": "BEST MOVES",
                "evaluation": "EVALUATION",
                "move_history": "MOVE HISTORY",
                "info_description": "This program is designed to analyze positions in Chinese chess (Xiangqi).\nThe program contains a graphical interface for user convenience,\nas well as a chess engine: Fairy-Stockfish (GPL-3.0)",
                "setup": "SETUP",
                "setup_active": "SETUP ACTIVE",
                "setup_panel": "POSITION SETUP",
                "setup_info": "Click on a piece, then click on the board to place. Click empty square to delete.",
                "red_pieces": "RED PIECES",
                "black_pieces": "BLACK PIECES",
                "clear_board": "CLEAR",
                "apply_position": "APPLY",
                "cancel": "CANCEL",
                "close": "CLOSE",
                "selected": "Selected",
                "no_piece_selected": "No piece selected",
                "red": "Red",
                "black": "Black",
                "start_position": "START",
                "turn_label": "Move:",
                "both_kings_required": "Both kings are required!",
                "king_already_exists": "King of this color already exists on the board!",
                "square_occupied": "Square is occupied!",
                "cannot_remove_king": "Cannot remove the king!",
                "no_piece_on_square": "No piece on this square",
                "king_outside_palace": "King must be inside the palace!",
                "advisor_outside_palace": "Advisor must be inside the palace!",
                "max_pawns_reached": "Maximum 5 pawns per side!",
                "max_cannons_reached": "Maximum 2 cannons per side!",
                "max_pieces_reached": "Maximum number of this piece reached!"
            },
            "ru": {
                "title": "Анализ Сянци",
                "best_move": "Лучший ход:",
                "score": "Оценка:",
                "analyze": "АНАЛИЗ",
                "flip": "ПОВЕРНУТЬ",
                "reset": "СБРОС",
                "undo": "ОТМЕНА",
                "thinking": "Анализ...",
                "error": "Ошибка движка",
                "ready": "✓ ГОТОВО",
                "no_move": "✗ НЕТ ХОДА",
                "invalid": "✗ НЕВЕРНО",
                "no_piece": "✗ НЕТ ФИГУРЫ",
                "engine_error": "✗ ОШИБКА ДВИЖКА",
                "analyzing": "⚙ АНАЛИЗ...",
                "starting": "⚙ ЗАПУСК...",
                "undo_done": "↩ ОТМЕНЕНО",
                "control_panel": "⚙ ПАНЕЛЬ УПРАВЛЕНИЯ",
                "move_list": "СПИСОК ХОДОВ",
                "best_moves": "ЛУЧШИЕ ХОДЫ",
                "evaluation": "ОЦЕНКА",
                "move_history": "ИСТОРИЯ ХОДОВ",
                "info_description": "Эта программа предназначена для анализа позиций в китайские шахматы (Сянци).\nПрограмма содержит графический интерфейс для удобства пользователя,\nа также шахматный движок: Fairy-Stockfish (GPL-3.0)",
                "setup": "РАССТАНОВКА",
                "setup_active": "РАССТАНОВКА",
                "setup_panel": "РАССТАНОВКА ПОЗИЦИИ",
                "setup_info": "Выберите фигуру, затем кликните на доску. Пустой квадрат - удалить.",
                "red_pieces": "КРАСНЫЕ",
                "black_pieces": "ЧЁРНЫЕ",
                "clear_board": "ОЧИСТИТЬ",
                "apply_position": "ПРИМЕНИТЬ",
                "cancel": "ОТМЕНА",
                "close": "ЗАКРЫТЬ",
                "selected": "Выбрана",
                "no_piece_selected": "Фигура не выбрана",
                "red": "Красные",
                "black": "Чёрные",
                "start_position": "НАЧАЛО",
                "turn_label": "ходят:",
                "both_kings_required": "Оба короля обязательны!",
                "king_already_exists": "Король этого цвета уже есть на доске!",
                "square_occupied": "Клетка занята!",
                "cannot_remove_king": "Нельзя удалить короля!",
                "no_piece_on_square": "На клетке нет фигуры",
                "king_outside_palace": "Король должен быть во дворце!",
                "advisor_outside_palace": "Советник должен быть во дворце!",
                "max_pawns_reached": "Максимум 5 пешек на сторону!",
                "max_cannons_reached": "Максимум 2 пушки на сторону!",
                "max_pieces_reached": "Достигнуто максимальное количество фигур этого типа!"
            },
            "zh": {
                "title": "象棋分析",
                "best_move": "最佳走法:",
                "score": "分数:",
                "analyze": "分析",
                "flip": "翻转棋盘",
                "reset": "重置",
                "undo": "撤销",
                "thinking": "分析中...",
                "error": "引擎错误",
                "ready": "✓ 准备就绪",
                "no_move": "✗ 无走法",
                "invalid": "✗ 无效",
                "no_piece": "✗ 无棋子",
                "engine_error": "✗ 引擎错误",
                "analyzing": "⚙ 分析中...",
                "starting": "⚙ 启动中...",
                "undo_done": "↩ 已撤销",
                "control_panel": "⚙ 控制面板",
                "move_list": "走法列表",
                "best_moves": "最佳走法",
                "evaluation": "局面评估",
                "move_history": "历史走法",
                "info_description": "本程序用于分析中国象棋（象棋）的局面。\n程序包含用户友好的图形界面，\n以及象棋引擎：Fairy-Stockfish (GPL-3.0)",
                "setup": "摆棋",
                "setup_active": "摆棋中",
                "setup_panel": "摆棋",
                "setup_info": "选择棋子，点击棋盘放置。点击空格删除。",
                "red_pieces": "红方",
                "black_pieces": "黑方",
                "clear_board": "清空",
                "apply_position": "应用",
                "cancel": "取消",
                "close": "关闭",
                "selected": "已选择",
                "no_piece_selected": "未选择棋子",
                "red": "红方",
                "black": "黑方",
                "start_position": "初始",
                "turn_label": "走子：",
                "both_kings_required": "需要双方将帅！",
                "king_already_exists": "该颜色的将帅已存在！",
                "square_occupied": "此格已有棋子！",
                "cannot_remove_king": "不能删除将帅！",
                "no_piece_on_square": "此格无棋子",
                "king_outside_palace": "将帅必须在九宫格内！",
                "advisor_outside_palace": "士必须在九宫格内！",
                "max_pawns_reached": "每方最多5个兵！",
                "max_cannons_reached": "每方最多2个炮！",
                "max_pieces_reached": "已达到该棋子的最大数量！"
            },
            "vi": {
                "title": "Phân tích Cờ Tướng",
                "best_move": "Nước đi tốt nhất:",
                "score": "Điểm số:",
                "analyze": "PHÂN TÍCH",
                "flip": "XOAY BÀN",
                "reset": "ĐẶT LẠI",
                "undo": "HOÀN TÁC",
                "thinking": "Đang phân tích...",
                "error": "Lỗi động cơ",
                "ready": "✓ SẴN SÀNG",
                "no_move": "✗ KHÔNG CÓ NƯỚC",
                "invalid": "✗ KHÔNG HỢP LỆ",
                "no_piece": "✗ KHÔNG CÓ QUÂN",
                "engine_error": "✗ LỖI ĐỘNG CƠ",
                "analyzing": "⚙ ĐANG PHÂN TÍCH...",
                "starting": "⚙ ĐANG KHỞI ĐỘNG...",
                "undo_done": "↩ ĐÃ HOÀN TÁC",
                "control_panel": "⚙ BẢNG ĐIỀU KHIỂN",
                "move_list": "DANH SÁCH NƯỚC",
                "best_moves": "NƯỚC ĐI TỐT NHẤT",
                "evaluation": "ĐÁNH GIÁ",
                "move_history": "LỊCH SỬ NƯỚC ĐI",
                "info_description": "Chương trình này được thiết kế để phân tích các thế cờ trong cờ tướng.\nChương trình có giao diện đồ họa thân thiện với người dùng,\ncũng như engine cờ: Fairy-Stockfish (GPL-3.0)",
                "setup": "XẾP CỜ",
                "setup_active": "ĐANG XẾP",
                "setup_panel": "XẾP CỜ",
                "setup_info": "Chọn quân, bấm vào bàn cờ để đặt. Bấm ô trống để xóa.",
                "red_pieces": "QUÂN ĐỎ",
                "black_pieces": "QUÂN ĐEN",
                "clear_board": "XÓA",
                "apply_position": "ÁP DỤNG",
                "cancel": "HỦY",
                "close": "ĐÓNG",
                "selected": "Đã chọn",
                "no_piece_selected": "Chưa chọn quân",
                "red": "Đỏ",
                "black": "Đen",
                "start_position": "ĐẦU",
                "turn_label": "Đi trước:",
                "both_kings_required": "Cần cả hai tướng!",
                "king_already_exists": "Tướng màu này đã có trên bàn cờ!",
                "square_occupied": "Ô này đã có quân!",
                "cannot_remove_king": "Không thể xóa tướng!",
                "no_piece_on_square": "Không có quân trên ô này",
                "king_outside_palace": "Tướng phải ở trong cung!",
                "advisor_outside_palace": "Sĩ phải ở trong cung!",
                "max_pawns_reached": "Tối đa 5 tốt mỗi bên!",
                "max_cannons_reached": "Tối đa 2 pháo mỗi bên!",
                "max_pieces_reached": "Đã đạt số lượng tối đa quân này!"
            },
            "ms": {
                "title": "Analisis Xiangqi",
                "best_move": "Langkah terbaik:",
                "score": "Skor:",
                "analyze": "ANALISIS",
                "flip": "PAPAN TERBALIK",
                "reset": "SET SEMULA",
                "undo": "BATALKAN",
                "thinking": "Menganalisis...",
                "error": "Ralat enjin",
                "ready": "✓ SIAP",
                "no_move": "✗ TIADA LANGKAH",
                "invalid": "✗ TIDAK SAH",
                "no_piece": "✗ TIADA BUAH",
                "engine_error": "✗ RALAT ENJIN",
                "analyzing": "⚙ MENGANALISIS...",
                "starting": "⚙ MEMULAKAN...",
                "undo_done": "↩ DIBATALKAN",
                "control_panel": "⚙ PANEL KAWALAN",
                "move_list": "SENARAI LANGKAH",
                "best_moves": "LANGKAH TERBAIK",
                "evaluation": "PENILAIAN",
                "move_history": "SEJARAH LANGKAH",
                "info_description": "Program ini direka untuk menganalisis kedudukan dalam catur Cina (Xiangqi).\nProgram ini mengandungi antara muka grafik untuk kemudahan pengguna,\nserta enjin catur: Fairy-Stockfish (GPL-3.0)",
                "setup": "SUSUN",
                "setup_active": "SEDANG MENYUSUN",
                "setup_panel": "SUSUNAN",
                "setup_info": "Pilih buah, klik papan untuk letak. Klik kosong untuk padam.",
                "red_pieces": "BUAH MERAH",
                "black_pieces": "BUAH HITAM",
                "clear_board": "PADAM",
                "apply_position": "GUNA",
                "cancel": "BATAL",
                "close": "TUTUP",
                "selected": "Dipilih",
                "no_piece_selected": "Tiada buah dipilih",
                "red": "Merah",
                "black": "Hitam",
                "start_position": "MULA",
                "turn_label": "Langkah:",
                "both_kings_required": "Kedua raja diperlukan!",
                "king_already_exists": "Raja warna ini sudah ada di papan!",
                "square_occupied": "Petak ini sudah diisi!",
                "cannot_remove_king": "Tidak boleh membuang raja!",
                "no_piece_on_square": "Tiada buah di petak ini",
                "king_outside_palace": "Raja mesti berada di dalam istana!",
                "advisor_outside_palace": "Penasihat mesti berada di dalam istana!",
                "max_pawns_reached": "Maksimum 5 bidak setiap pihak!",
                "max_cannons_reached": "Maksimum 2 meriam setiap pihak!",
                "max_pieces_reached": "Maksimum bilangan buah ini telah dicapai!"
            }
        }

    def get(self, key):
        """
        Get translated text for a given key.
        
        Args:
            key: Translation key
            
        Returns:
            Translated string or key itself if not found
        """
        return self.texts[self.lang].get(key, key)

tr = Translator()